language: node_js

node_js:
  - "stable"

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x24"


before_script:
  - "export DISPLAY=:99.0"
  - "export SCREEN_WIDTH=1440"
  - "export SCREEN_HEIGHT=900"
  - "export SCREEN_DEPTH=24"
  - sleep 3 # give xvfb some time to start
