blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://stackoverflow.com/questions/tagged/jodit
    about: Please ask questions on Stack Overflow with the 'jodit' tag
  - name: Documentation
    url: https://xdsoft.net/jodit/docs/
    about: Check the documentation for usage examples
