name: Run tests

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'New version') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4 #Setup Node
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Run Karma Tests
      run: |
        npm ci --legacy-peer-deps
        make lint
        make test uglify=true fat=true
